### ISSUE TITLE
Project Name

### ISSUE THREAD

**Issue by eayus** [eayus/sirdi#12]
In typical open-source project fashion, the name `sirdi` was just originally chosen as a "temporary" name, but it seems to have stuck for now. However, if people dislike the name, now is probably the time to change it.

If you have particular preference for a name, comment below!

- The main requirement for a name is that it is easily "google-able" (we don't need another "idris elba" incident).

- I think the name should also be relatively short (I'd say 6/7 characters is probably the limit, so it is quick to type).

- Maybe it would be nice if we named the package manager after an "Ivor the Engine" character (which is where the name `Idris` comes from)? (https://en.wikipedia.org/wiki/Ivor_the_Engine#Characters)

**Comment by JonathanLorimer** [comment]
I like the name `ivor`, it is the steam engine from the same cartoon as idris, also steam engines carry packages / goods around so its kind of fitting. No strong preference though, just figured I would pitch this idea in.

**Comment by eayus** [comment]
@JonathanLorimer Unfortunately `Ivor` is already taken (https://eb.host.cs.st-andrews.ac.uk/drafts/ivor.pdf), Edwin has used it for one of his previous works. Otherwise it'd be a great name

**Comment by eayus** [comment]
As for other names from Ivor the Engine, I kind of like `dai` and `eli` but I'm not sure whether they are already in use, and just from a quick google it seems `eli` may not be the most google-able.

**Comment by JonathanLorimer** [comment]
Also `dai` might be confusing when google-ing due to a cryptocurrency of the same name. Maybe `daian` for idris's brother? Also `boiler` or `freight` are decent options that relate back to trains. `tender` is the car that carries all the fuel in a steam engine so that might be interesting, but i'm afraid the reference will be lost on most people.

**Comment by eayus** [comment]
Ah I didn't realise `dai` was a crypto currency as well, I think that name is not ideal then either. I also like `daian`. `olwen` is another option, which is Idris's wife.

**Comment by JonathanLorimer** [comment]
I like both `daian` and `olwen`

**Comment by ohad** [comment]
I'm happy with sirdi --- a good name!

**Comment by jfdm** [comment]
one could always go for chipshop, or SmokeHill. These are good memorable alternatives.

**Comment by eayus** [comment]
Ok looks like we'll just stick with `sirdi`, people are already familiar with the name now, and so a change seems a bit pointless :D
